### ISSUE TITLE
Implement the right ap() method

### ISSUE THREAD

**Issue by thomasvargiu** [functional-php/fantasy-land#16]
The `ap()` method in `Apply` isn't correct, but seems inverted.

it should be 
```
ap :: Apply f => f a ~> f (a -> b) -> f b
```

Since the `f (a -> b)` should be the same of `f a` it's possible to implement the right method.
This is an example of the Identity monad:

```php
/**
 * @template T
 */
class Identity
{
   /**
     * @template U
     * @template C as callable(T): U
     *
     * @param FantasyLand\Apply<C> $applicative
     * @return FantasyLand\Apply<U>
     */
    public function ap2(FantasyLand\Apply $applicative): FantasyLand\Apply
    {
        if (! $applicative instanceof self) {
            throw new \LogicException(sprintf('Applicative must be an instance of %s', self::class));
        }
        return $applicative->bind(function (callable $f) {
            return self::of($f($this->value));
        });
    }
}
```

In this way it's statically correct too.

This is a BC, so a new 2.0 version is necessary.

**Comment by AlexanderAllen** [comment]
I wish I had a handle on the generics notation like you do, I'm envious. I'm just implementing fantasy land from scratch (using the book and functional php packages for references) for fun and learning.

To return the exact type contained in a Monad to PHPStan, even through an applicative method like you have above... a man can dream :)

**Comment by AlexanderAllen** [comment]
When copying some of these types to phpstan.org they don't compile.

For example: https://phpstan.org/r/75573289-03f7-4e7d-9142-5b28842872ea
