### ISSUE TITLE
Add template types to DocBlocks for static analysis tools

### ISSUE THREAD

**Issue by athrawes** [functional-php/fantasy-land#20]
In the last several years, static analysis tools such as [Psalm](https://github.com/vimeo/psalm) and [PhpStan](https://github.com/phpstan/phpstan) have become relatively popular to use for PHP development.

In general, these tools are able to parse and use generics in docblocks to provide additional type hints during analysis.
Having these generic types hinted in code, especially in libraries such as this, make life in PHP much nicer.

Would you consider adding these in?

**Comment by athrawes** [comment]
I've added a PR to add these to a majority of functions and classes here: https://github.com/functional-php/fantasy-land/pull/21

**Comment by krtek4** [comment]
PR merged
