### ISSUE TITLE
Add project to packagist.org

### ISSUE THREAD

**Issue by widmogrod** [functional-php/fantasy-land#3]
Add project to https://packagist.org

**Comment by widmogrod** [comment]
@krtek4 could you add me to the packagist organisation?
Unfortunately I cannot add this library to the organisation https://packagist.org/packages/functional-php/

**Comment by krtek4** [comment]
It should be ok now. Otherwise I'll add the package myself and add you as a maintainer.

**Comment by widmogrod** [comment]
Thank you! It's OK now.
